const MATCHES = [
  { num: 1,  teams: "Mexico vs South Africa",     date: "11 JUN 26", time: "16:00", stadium: "Mexico City Stadium",     entrance: "A/B" },
  { num: 2,  teams: "South Korea vs Playoff D", date: "11 JUN 26", time: "22:00", stadium: "Guadalajara Stadium",     entrance: "A/B/C" },
  { num: 3,  teams: "Canada vs Playoff A",      date: "12 JUN 26", time: "16:00", stadium: "Toronto Stadium",         entrance: "A/B" },
  { num: 4,  teams: "USA vs Paraguay",          date: "12 JUN 26", time: "22:00", stadium: "Los Angeles Stadium",     entrance: "B/C/D" },
  { num: 5,  teams: "Qatar vs Switzerland",     date: "13 JUN 26", time: "16:00", stadium: "San Francisco Bay Stadium", entrance: "A/B/C" },
  { num: 6,  teams: "Brazil vs Morocco",        date: "13 JUN 26", time: "22:00", stadium: "New York New Jersey Stadium", entrance: "B/C/D/E" },
  { num: 7,  teams: "Haiti vs Scotland",        date: "14 JUN 26", time: "16:00", stadium: "Boston Stadium",          entrance: "A/B" },
  { num: 8,  teams: "Australia vs Playoff C",   date: "14 JUN 26", time: "22:00", stadium: "Vancouver Stadium",       entrance: "A/B/C" },
  { num: 9,  teams: "Germany vs Curaçao",       date: "15 JUN 26", time: "16:00", stadium: "Houston Stadium",         entrance: "B/C" },
  { num: 10, teams: "Netherlands vs Japan",     date: "15 JUN 26", time: "22:00", stadium: "Dallas Stadium",          entrance: "B/C/D" },
  { num: 11, teams: "Ivory Coast vs Ecuador",   date: "16 JUN 26", time: "16:00", stadium: "Philadelphia Stadium",    entrance: "A/B/C" },
  { num: 12, teams: "UEFA Playoff B vs Tunisia", date: "16 JUN 26", time: "22:00", stadium: "Monterrey Stadium",      entrance: "B/C/D/E" },
  { num: 13, teams: "Spain vs Cape Verde",      date: "17 JUN 26", time: "16:00", stadium: "Atlanta Stadium",         entrance: "A/B" },
  { num: 14, teams: "Belgium vs Egypt",         date: "17 JUN 26", time: "22:00", stadium: "Seattle Stadium",         entrance: "B/C/D" },
  { num: 15, teams: "Saudi Arabia vs Uruguay",  date: "18 JUN 26", time: "16:00", stadium: "Miami Stadium",           entrance: "A/B/C" },
  { num: 16, teams: "Iran vs New Zealand",      date: "18 JUN 26", time: "22:00", stadium: "Los Angeles Stadium",     entrance: "B/C/D/E" },
  { num: 17, teams: "France vs Senegal",        date: "19 JUN 26", time: "16:00", stadium: "New York New Jersey Stadium", entrance: "A/B" },
  { num: 18, teams: "Playoff B vs Norway",      date: "19 JUN 26", time: "22:00", stadium: "Boston Stadium",          entrance: "B/C" },
  { num: 19, teams: "Argentina vs Algeria",     date: "20 JUN 26", time: "16:00", stadium: "Kansas City Stadium",     entrance: "A/B/C" },
  { num: 20, teams: "Austria vs Jordan",        date: "20 JUN 26", time: "22:00", stadium: "San Francisco Bay Stadium", entrance: "B/C/D" },
  { num: 21, teams: "Portugal vs Playoff D",    date: "21 JUN 26", time: "16:00", stadium: "Houston Stadium",         entrance: "A/B" },
  { num: 22, teams: "England vs Croatia",       date: "21 JUN 26", time: "22:00", stadium: "Boston Stadium",          entrance: "B/C/D/E" },
  { num: 23, teams: "Ghana vs Panama",          date: "22 JUN 26", time: "16:00", stadium: "Toronto Stadium",         entrance: "A/B/C" },
  { num: 24, teams: "Uzbekistan vs Colombia",   date: "22 JUN 26", time: "22:00", stadium: "Mexico City Stadium",     entrance: "B/C/D" },
  { num: 25, teams: "Scotland vs Morocco",      date: "23 JUN 26", time: "16:00", stadium: "Miami Stadium",           entrance: "A/B" },
  { num: 26, teams: "Brazil vs Haiti",          date: "23 JUN 26", time: "22:00", stadium: "Philadelphia Stadium",    entrance: "B/C/D/E" },
  { num: 27, teams: "Switzerland vs Playoff A", date: "24 JUN 26", time: "16:00", stadium: "Vancouver Stadium",       entrance: "A/B/C" },
  { num: 28, teams: "Canada vs Qatar",          date: "24 JUN 26", time: "22:00", stadium: "Seattle Stadium",         entrance: "B/C" },
  { num: 29, teams: "Mexico vs South Korea",    date: "25 JUN 26", time: "16:00", stadium: "Guadalajara Stadium",     entrance: "A/B" },
  { num: 30, teams: "Playoff D vs South Africa", date: "25 JUN 26", time: "22:00", stadium: "Atlanta Stadium",        entrance: "B/C/D" },
  { num: 31, teams: "USA vs Australia",         date: "26 JUN 26", time: "16:00", stadium: "Seattle Stadium",         entrance: "A/B/C" },
  { num: 32, teams: "Paraguay vs Playoff C",    date: "26 JUN 26", time: "22:00", stadium: "San Francisco Bay Stadium", entrance: "B/C/D/E" },
  { num: 33, teams: "Ecuador vs Germany",       date: "27 JUN 26", time: "16:00", stadium: "New York New Jersey Stadium", entrance: "A/B" },
  { num: 34, teams: "Curaçao vs Ivory Coast",   date: "27 JUN 26", time: "22:00", stadium: "Philadelphia Stadium",    entrance: "B/C" },
  { num: 35, teams: "Tunisia vs Japan",         date: "28 JUN 26", time: "16:00", stadium: "Dallas Stadium",          entrance: "B/C/D/E" },
  { num: 36, teams: "Tunisia vs Japan",         date: "20 JUN 26", time: "22:00", stadium: "Monterrey Stadium",       entrance: "B/C/D/E" },
  { num: 37, teams: "Norway vs Senegal",        date: "28 JUN 26", time: "22:00", stadium: "Houston Stadium",         entrance: "A/B/C" },
  { num: 38, teams: "Egypt vs Iran",            date: "29 JUN 26", time: "16:00", stadium: "Los Angeles Stadium",     entrance: "B/C/D" },
  { num: 39, teams: "New Zealand vs Belgium",   date: "29 JUN 26", time: "22:00", stadium: "Vancouver Stadium",       entrance: "A/B" },
  { num: 40, teams: "Spain vs Saudi Arabia",    date: "30 JUN 26", time: "16:00", stadium: "Atlanta Stadium",         entrance: "B/C/D/E" },
];
